export const ADD_CATEGORIES = "ADD_CATEGORIES";
export const CATEGORIES_LOADING = "CATEGORIES_LOADING";
export const CATEGORIES_FAILED = "CATEGORIES_FAILED";

export const ADD_DIRECTORY = "ADD_DIRECTORY";
export const DIRECTORY_LOADING = "DIRECTORY_LOADING";
export const DIRECTORY_FAILED = "DIRECTORY_FAILED";
